### ISSUE TITLE
Unstyled scrollbars

### ISSUE THREAD

**Issue by visualcookie** [cpsdqs/dash-ui#1]
Good UI and Syntax theme, but for me on Windows the Scrollbars sadly are unstyled. (See comparision below)

One Dark UI:
![image](https://cloud.githubusercontent.com/assets/1857554/26282550/c5a6ca34-3e13-11e7-99b3-65e2d8cc609d.png)

Dash UI:
![image](https://cloud.githubusercontent.com/assets/1857554/26282555/d416c402-3e13-11e7-8514-8cb2043bc5c9.png)

**Comment by cpsdqs** [comment]
Thanks! It should be fixed now in 0.1.1

**Comment by visualcookie** [comment]
Amazing, thanks. 👍
