### ISSUE TITLE
Collision with `file-icons`

### ISSUE THREAD

**Issue by visualcookie** [cpsdqs/dash-ui#2]
When Dash UI is enabled, the Icons from the package `file-icons` don't render anymore.

**Comment by zraffer** [comment]
file-icons are not shown again. help!

**Comment by cpsdqs** [comment]
@zraffer what Atom version are you using? It seems to work fine for me in 1.20 when I disable file icons in the dash-ui settings

**Comment by zraffer** [comment]
Oh, sorry, I have not checked settings. It works ok now! Thank you.
